on: [push]

jobs:
  test_upload:
    runs-on: ubuntu-latest
    name: test sftp upload
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create Test file
        run: echo "test" > test.txt  
      - name: test upload step
        uses: ./ # Uses an action in the root directory
        id: test1
        with:
          user: ${{secrets.REPO_USER}}
          server: ${{secrets.REPO_SERVER}}
          privateKey: ${{secrets.REPO_KEY}}
          localFile: 'test.txt'
          remoteDir: ${{secrets.REMOTE_PATH}}
      